# Generated by Django 5.0.1 on 2024-01-30 02:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_alter_question_order_alter_question_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Answer",
            new_name="UserResponse",
        ),
        migrations.RenameField(
            model_name="userresponse",
            old_name="text",
            new_name="response",
        ),
    ]
