# Generated by Django 5.0.1 on 2024-02-01 01:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0005_alter_question_id_alter_survey_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SurveyUser",
            new_name="UserSurveySubscription",
        ),
    ]
