# Generated by Django 5.0.1 on 2024-01-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("survey", "order")},
        ),
    ]
