# Generated by Django 5.0.1 on 2024-01-30 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "twilio_service",
            "0002_question_order_survey_description_alter_answer_text_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="survey",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Survey",
        ),
    ]
