# Generated by Django 5.0.1 on 2024-01-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twilio_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
